### ISSUE TITLE
Coinbase::Wallet::InvalidRequestError: Invalid currency (BTC-USD)

### ISSUE THREAD

**Issue by etagwerker** [coinbase/coinbase-ruby#103]
Hello,

I tried to use the examples in the documentation but I got this error: 

```
Coinbase::Wallet::InvalidRequestError: Invalid currency (BTC-USD)
/Users/etagwerker/.rvm/gems/ruby-2.3.3@coinbase/gems/coinbase-4.1.0/lib/coinbase/wallet/api_errors.rb:29:in `check_response_status'
/Users/etagwerker/.rvm/gems/ruby-2.3.3@coinbase/gems/coinbase-4.1.0/lib/coinbase/wallet/adapters/net_http.rb:36:in `http_verb'
/Users/etagwerker/.rvm/gems/ruby-2.3.3@coinbase/gems/coinbase-4.1.0/lib/coinbase/wallet/api_client.rb:649:in `get'
/Users/etagwerker/.rvm/gems/ruby-2.3.3@coinbase/gems/coinbase-4.1.0/lib/coinbase/wallet/api_client.rb:31:in `buy_price'
/Users/etagwerker/Projects/coinbase-alerter/Rakefile:13:in `block in <top (required)>'
```

The code that I tried to use:

```
client.buy_price(currency: 'BTC-USD')
client.sell_price(currency: 'ETH-BTC')
client.spot_price(currency: 'BTC-EUR')
```

Now it works if I change my code to look like this: 

```
client.buy_price(currency_pair: 'BTC-USD')
client.sell_price(currency_pair: 'ETH-BTC')
client.spot_price(currency_pair: 'BTC-EUR')
```

Maybe the README is out of date? 

Please let me know.

Thanks!

**Comment by colinbm** [comment]
It looks like the docs are correct, but the version available through rubygems is out of date.

So you can do:

- `client.buy_price` which uses BTC-USD
- `client.buy_price(currency: 'GBP')` which uses BTC-GBP (always bitcoin)
- `client.buy_price(currency_pair: 'ETH-EUR')` which gives you full control.

So install with Gemfile, and use `gem 'coinbase', github: 'coinbase/coinbase-ruby'` and it *should work*.

**Comment by scarrick68** [comment]
I went for
- `gem 'coinbase', :git => 'https://github.com/coinbase/coinbase-ruby.git', :ref => '51780c7b7e65adc805e061926b1138db83b7bcb1'`
in case the gem gets updated and breaks something, I'm frozen on that commit SHA.

@colinbm example is correct, but the docs are not. `client.sell_price(currency: 'ETH-BTC')` but that'll fail even with the newest version because it tries to create the string `'BTC-ETH-BTC'` by appending whatever you pass in to a `'BTC'` prefix. It only takes the currency pair as is if you use the currency_pair param. The ruby gem is out of date and doesn't support currency pairs at all, only BTC-USD.

**Comment by sds** [comment]
Apologies for the delay. Version [4.2.0](https://rubygems.org/gems/coinbase/versions/4.2.0) has been released!
