### ISSUE TITLE
Amount Conversion doesn't work properly

### ISSUE THREAD

**Issue by parabuzzle** [coinbase/coinbase-ruby#98]
```
2.3.1 :022 > client.accounts[1].balance['amount']
 => "4.73257967" # Correct Amount
2.3.1 :023 > client.accounts[1].balance.amount.to_s
 => "0.473257967E1" # Incorrect Amount
###
2.3.1 :026 > client.accounts[4].balance.amount.to_s
 => "0.36772081E0" # Correct Amount
2.3.1 :027 > client.accounts[4].balance['amount']
 => "0.36772081" # Correct Amount
```

Using version 4.1.0

**Comment by sds** [comment]
Hey @parabuzzle, apologies for the slow response here.

The amounts are correct, you're just outputting them in scientific notation (notice the `E1` at the end of the second output).

Since `amount` is a `BigDecimal` object, calling `to_s` returns the number formatted in scientific notation. To customize this output, see the documentation for [`BigDecimal#to_s`](https://ruby-doc.org/stdlib-2.3.1/libdoc/bigdecimal/rdoc/BigDecimal.html#method-i-to_s).
